# Generated by Django 2.2.12 on 2022-01-08 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20220108_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos_post',
            name='detect_videos',
            field=models.FileField(blank=True, default='', upload_to='videos/detect/'),
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='videos',
            field=models.FileField(blank=True, default='', upload_to='videos/manipulate/'),
        ),
    ]
