# Generated by Django 2.2.4 on 2022-02-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20220108_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='post',
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='compressed_format',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='detect_videos',
            field=models.FileField(blank=True, default='', upload_to='../in_out_videos/result'),
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='forging_method',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='videos_post',
            name='videos',
            field=models.FileField(blank=True, default='', upload_to='../in_out_videos/manipulate'),
        ),
        migrations.DeleteModel(
            name='Compressed_format',
        ),
        migrations.DeleteModel(
            name='Forging_method',
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
