# Generated by Django 2.2.4 on 2022-03-07 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20220214_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos_post',
            name='created',
        ),
        migrations.RemoveField(
            model_name='videos_post',
            name='user',
        ),
    ]
